baseURL = 'https://ghrn.me/'
languageCode = 'en-us'
title = 'Gabriell Nascimento'
theme = 'nostyleplease'

[params]
favicon = 'favicon.ico'
custom_css = ["css/custom.css"]

  [params.theme_config]
  appearance = "light"
